### ISSUE TITLE
アカウント削除,ログアウトモーダル実装

### ISSUE THREAD

**Issue by kensiiwasaki** [qin-todo-team-i/qin-todo-team-i#24]
#46 が終わりましたら
そのままモーダルの作成もお願いします！
モーダルは出てくるだけで押しても特に動作はなしで大丈夫です！

<img width="551" alt="スクリーンショット 2022-03-02 12 14 26" src="https://user-images.githubusercontent.com/81737432/156288131-f694c95e-af8e-4498-a1fb-8f1713cd67c7.png">

**Comment by shooist** [comment]
@kensiiwasaki お疲れさまです！
こちらPLマージ頂いているようですので、Closeして問題ないでしょうか？
