### ISSUE TITLE
testの削除

### ISSUE THREAD

**Issue by kensiiwasaki** [qin-todo-team-i/qin-todo-team-i#31]
画像のtestという文字を削除する

<img width="206" alt="スクリーンショット 2022-02-22 11 00 56" src="https://user-images.githubusercontent.com/81737432/155049545-fe730b45-fc42-433e-a359-de0283da01be.png">

**Comment by soeru** [comment]
package-lockとyarn.lock誤って入れてしまいました。次から外します〜！
