### ISSUE TITLE
アカウント設定ページの修正

### ISSUE THREAD

**Issue by kensiiwasaki** [qin-todo-team-i/qin-todo-team-i#38]
デザインが確定したのでこちらに変更でお願いします！
<img width="784" alt="スクリーンショット 2022-02-25 13 48 24" src="https://user-images.githubusercontent.com/81737432/155655653-5ea33765-e4fd-4f11-a843-ec857509bc2c.png">

- この部分はホバーした時にグレー
<img width="215" alt="スクリーンショット 2022-02-25 13 51 13" src="https://user-images.githubusercontent.com/81737432/155655914-d95dc0db-8c86-4163-a307-a38a4fdb760b.png">

**Comment by soeru** [comment]
進捗共有です。ドロップダウンメニューらしきもののwidthとpositionのシンプルな実装が思いつかず苦戦中です。absoluteにしたので、rightを動的に出力しないといけなくなり、複雑になりつつあります。
https://user-images.githubusercontent.com/14804989/155916431-a5296cfe-7be8-40b6-97ef-27552bfe0974.mp4

**Comment by soeru** [comment]
モバイルだとヘッダーは非表示のようなので、そこもまだ実装が見えていないため、もし調べてみてもわからなかったら苦戦するかもです。

**Comment by soeru** [comment]
現状ドロップダウンメニューのrightは一旦0に指定してあります。

**Comment by kensiiwasaki** [comment]
> 進捗共有です。ドロップダウンメニューらしきもののwidthとpositionのシンプルな実装が思いつかず苦戦中です。absoluteにしたので、rightを動的に出力しないといけなくなり、複雑になりつつあります。 https://user-images.githubusercontent.com/14804989/155916431-a5296cfe-7be8-40b6-97ef-27552bfe0974.mp4

right もしくは padding-right の単位を％にしてみても同じ状況でしょうか？？

**Comment by kensiiwasaki** [comment]
> モバイルだとヘッダーは非表示のようなので、そこもまだ実装が見えていないため、もし調べてみてもわからなかったら苦戦するかもです。

モバイル版はモバイル版でそのままデザインを採用するので現状のように一定の画面幅で非表示で問題ないです！

**Comment by soeru** [comment]
> 

ご確認ありがとうございます！
widthとpositionの動的に出力するイメージはこちらです！

1024pxがブレークポイントで、アイコンの位置に応じて変更させています。

↓のような見るたびに何をしているのか全くわからないコードになっちゃうんです、、
おそらく私も2日後に見たらわからないです！
`right-[max(calc((((100vw-1024px)/2)-calc(100vw/12))+18px),0px)]`


https://user-images.githubusercontent.com/14804989/155923823-ad5a8b5b-ff82-470c-8b02-0153b1ecf6ea.mp4

**Comment by soeru** [comment]
下記3つに依存しているので、一つでも変更したら、またこの数式を理解しなくてはいけなくなり、保守性は最悪です。もっとシンプルに実装する方法が絶対あるはずで、そもそもの根幹から間違えている気がしてなりません。

1. Headerのmax-widthが1024px
2. アイコンの横幅が36px
3. ドロップダウンメニューの横幅がvwの6分の1

**Comment by kensiiwasaki** [comment]
@soeru 
なるほどです！
コードも見てみましたが現状この複雑な動作をシンプルにするにはぱっとは思いつきませんね〜🤔

何よりヘッダーに関しては今後修正することは間違いないと思っているので、そこに依存してしまうと後に誰かが再度苦戦するのは明白な気もします。
あまり1つのタスクに時間を割いてもあれなので、
1. 数式に関してわかりやすくコメントを残す
2. 一旦相対指定で実装する
3. 特にレスポンシブを考えず一旦UIのみだけにとどめる

のいずれかを選択していただいて次に進んでいただくしかなさそうですね🤔
後々思いついた時だったりに再度試してみてもらうって形で

**Comment by soeru** [comment]
わかりました！
コメント残しておいて、プロフィールページの実装に進みますね！

**Comment by kensiiwasaki** [comment]
@soeru 
お願いします！
コメントしたらそのままプルリクエスト出してもらって大丈夫です！

**Comment by mitochon9** [comment]
@soeru 
話が進んでしまっている中申し訳ないのですが、このような実装だとどうでしょうか？
意図が違っていたらすみません💦

<img width="1206" alt="relative-absolute" src="https://user-images.githubusercontent.com/79145642/155930634-c1024a54-147f-4d76-b200-f64130c0ea6e.png">

https://user-images.githubusercontent.com/79145642/155930650-bb62468b-3671-4c2e-b7a5-f78de2039687.mov


追記：コード見た感じだといけそうなんですけどね... 余計なコメントだったらすみません🙏

**Comment by kensiiwasaki** [comment]
@mitochon9 
modalのwidthはどのように変化するのでしょうか？？

**Comment by mitochon9** [comment]
親要素で設定した relative の width を引き継いで、 w-full だと折り返されてしまうので width は w-〇〇 などで固定してもいいかと思いますが、どうでしょう？

`      <div className="relative">
        <Link href="#">
          <a>
            <Image src="/person.png" alt="logo" width={36} height={36} />
          </a>
        </Link>

        <div className="absolute text-center hidden w-28 border p-4 lg:block -bottom-16 left-1/2 -translate-x-1/2">
          modal
        </div>
      </div>
`

https://user-images.githubusercontent.com/79145642/155931824-0e68ca73-31dc-4f3a-bb64-978a0df473d2.mov

**Comment by mitochon9** [comment]
@kensiiwasaki

親要素で設定した relative の width を引き継いで、 w-full だと折り返されてしまうので width は w-〇〇 などで固定してもいいかと思いますが、どうでしょう？

コード：
https://thinkable-pea-9e4.notion.site/relative-absolute-569993e4c3df4ae3ab002a09b9c6386e

動画：

https://user-images.githubusercontent.com/79145642/155932554-595fea54-6093-4ac0-8f09-cc6bbd359e74.mov

**Comment by kensiiwasaki** [comment]
@mitochon9 
確かにデザイン的もrelative-absoluteの関係っぽいですね、、、
widthは固定でもいいですが、パッと思いついた感じだと
min-widthとmax-widthをそれぞれ指定してwidthを％で相対指定にしたほうがよさそうかも🤔

一旦保留ですが、色々試してみてベストプラクティス探しますか！

**Comment by mitochon9** [comment]
@kensiiwasaki 
w-1/6 が何かしらか引き起こしていそうな気はします。
min-width, max-width を指定している方が意図しないデザイン崩れを防げそうですね！
承知しました！
