### ISSUE TITLE
HeaderとLayout コンポーネントの作成

### ISSUE THREAD

**Issue by kensiiwasaki** [qin-todo-team-i/qin-todo-team-i#6]
## 内容
- Header コンポーネントを作成する
- Header コンポーネントを利用してLayoutコンポーネントを作成する

## 画像
header
<img width="700" alt="スクリーンショット 2022-02-14 10 33 57" src="https://user-images.githubusercontent.com/81737432/153785725-adbe4e7c-cc5c-4cce-92ae-10fa66a536b9.png">

layout
<img width="614" alt="スクリーンショット 2022-02-14 10 47 04" src="https://user-images.githubusercontent.com/81737432/153786546-03331013-855b-4a91-a5d0-9dc394b5c4b8.png">

**Comment by kensiiwasaki** [comment]
@mitochon9 
よろしくお願いします！

**Comment by mitochon9** [comment]
@kensiiwasaki 
プルリクエストを出してみました！
ご確認よろしくお願いします！

**Comment by kensiiwasaki** [comment]
@mitochon9 一旦閉じました！
